language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_PACKAGE="Django>=1.5,<1.6"
  - DJANGO_PACKAGE="Django>=1.6,<1.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
  - pip install $DJANGO_PACKAGE --use-mirrors
  - pip install . --use-mirrors
  - pip install coveralls
script:
  - django-admin.py --version
  - coverage run manage.py test
after_success:
  - coveralls
branches:
  only:
    - master